### ISSUE TITLE
Performance optimize for prod

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/rms-app#25]
Um die Seite letztendlich deployen zu können, sollten wir noch ein wenig aufräumen. Nicht zuletzt sollten unötige Inhalte aus dem Theme entfernt werden, das bis dato noch bis auf kleinere Anpassungen exakt dem statischen Mockup/Demo entspricht

# Todos:

- [x] Cleanup theme templates (only keep the ones used in Diazo rules.xml
- [x] Rethink javascript concat and files
- [x] Remove unneeded styles
- [x] Setup Plone backend for optimal performance (remove default navigation portlet and add several other settings that prevent unnecessary rendering of content)
- [x] Evaluate, if we can remove/replace font-awesome (no need to loud an icon font when we use 4 (!) icons) - potential alternative: https://github.com/saeedalipoor/icono

## Optional

- Use loadCss and criticalcss (we only serve 2 public views - doable)
- Optimize image integration in Plone CMS backend
